default:
  tags:
    - docker
  image: alpine

include:
  - local: "/gitlab-ci/includes.yml"

stages:
  - update-version
  - code-quality
  - code-test
  - application-build
  - code-analysis
  - site-report
  - image-build
  - container-image-test
  - component-test
  - image-push
  - update-project-metadata
  - generate-api-docs
  - pages
  - open-source
  - create-schedules

variables:
  # Product
  PRODUCT: ds1500 # Used by the push fragments to build artifact destinations
  SERVICE_NAME: "controller" # Used by pages-tech-docs fragment to create docs site
  # Project Badges
  REPO_OWNER: "Team Falcon"
  REPO_PATTERN: "V3 CI"
  # Config
  BUILD_TYPE: "MAVEN"
  MAVEN_IMAGE: "maven:3.9.6-eclipse-temurin-17"
  MVN_OPTS: "-DLOG_LEVEL=INFO"
  MVN_CLI_OPTS: "--batch-mode"
  GITHUB_REPO_NAME: "ms-ds1500-controller" # Used for open-source fragment

required-fragment-check:
  variables:
    RULESET: MAVEN_CI

maven-cucumber:
  extends: .docker-compose-run
  stage: code-test
  variables:
    DOCKER_COMPOSE_FILE: "docker-compose.yml"
    DOCKER_COMPOSE_COMMAND: "--exit-code-from cucumber-tests"
    MVN_M2: "./.m2-local/"
  cache:
    key: ${CACHE_KEY}
    paths:
      - .m2-local/
    when: 'always'

create-develop-nightly-schedule:
  extends: .add-schedule
  variables:
    SCHEDULE_NAME: Nightly-Develop-CI-Build
    SCHEDULE_BRANCH: develop
    SCHEDULE_CRON: "0 20 * * *"
    RANDOMIZE_MINS: "true"

