include:
    #.pre
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/credential-check'
      ref: 2-3-1
      file: 'ci-include-credential-check.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/fragment-version-check'
      ref: 2.4.0
      file: 'ci-include-fragment-version-check.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/required-fragment-check'
      ref: 2.14.0
      file: 'ci-include-required-fragment-check.yml'
    #update-version
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/update-semver'
      ref: 4.5.0
      file: 'ci-include-update-semver.yml'
    #code-quality
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/gitleaks'
      ref: 3.1.2
      file: 'ci-include-gitleaks.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/shell-check'
      ref: 3-1-4
      file: 'ci-include-shell-check.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/todo-checker'
      ref: 2-1-4
      file: 'ci-include-todo-checker.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/maven-checkstyle-lint'
      ref: 3.4.0
      file: 'ci-include-maven-checkstyle-lint.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/docker-lint'
      ref: 2.5.1
      file: 'ci-include-docker-lint.yml'
    #code-test
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/maven-api-test'
      ref: 3.7.0
      file: 'ci-include-maven-api-test.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/docker-compose-run'
      ref: 3.4.0
      file: 'ci-include-docker-compose-run.yml'
    #application-build
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/maven-api-build'
      ref: 3.4.0
      file: 'ci-include-maven-api-build.yml'
    #code-analysis
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/maven-api-pitest'
      ref: 3.4.1
      file: 'ci-include-maven-api-pitest.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/maven-api-spotbugs'
      ref: 3.4.0
      file: 'ci-include-maven-api-spotbugs.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/gitlab-sast'
      ref: 2.0.0
      file: 'ci-include-gitlab-sast.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/maven-dependency-version-check'
      ref: 2.3.2
      file: 'ci-include-maven-version-check.yml'
  #site-report
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/maven-api-site'
      ref: 3.3.0
      file: 'ci-include-maven-api-site.yml'
    #image-build
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/docker-build'
      ref: 5.1.1
      file: 'ci-include-docker-build.yml'
    #container-image-test
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/sast-container-check'
      ref: 2.11.0
      file: 'ci-include-sast-container-check.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/trivy-container-check'
      ref: 2.21.0
      file: 'ci-include-trivy-container-check.yml'
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/container-structure-test'
      ref: 2.10.0
      file: 'ci-include-container-structure-test.yml'
    #image-push
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/push-to-ecr'
      ref: 4.7.1
      file: 'ci-include-push-to-ecr.yml'
    #update-project-metadata
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/create-project-badges'
      ref: 2.5.0
      file: 'ci-include-create-project-badges.yml'
    #pages
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/pages-tech-docs'
      ref: 5.1.0
      file: 'ci-include-pages_tech_docs.yml'
    #open-source
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/open-source'
      ref: 2.3.0
      file: 'ci-include-open-source.yml'
    #create-schedules
    - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/schedule-creation'
      ref: 2.7.0
      file: 'ci-include-schedule-creation.yml'
